name: ArashiPolice
version: ${project.version}
main: io.github.smile_ns.arashipolice.ArashiPolice
api-version: 1.16

commands:
  police:
    usage: /police [args]

permissions:
  police:
    default: op